# ResNet

In [1]:
import keras
import numpy as np


$y = \gamma \cdot \hat{x} + \beta$


In [ ]:
a = np.arange(18, dtype=float).reshape(1, 3, 2, 3)

bn = keras.layers.BatchNormalization(beta_initializer="zeros", gamma_initializer="ones")

result = bn(a)

print(a)
print("-" * 20)
print(result.numpy())


[[[[ 0.  1.  2.]
   [ 3.  4.  5.]]

  [[ 6.  7.  8.]
   [ 9. 10. 11.]]

  [[12. 13. 14.]
   [15. 16. 17.]]]]
--------------------
[[[[ 1.         1.9995003  2.9990005]
   [ 3.998501   4.998001   5.997502 ]]

  [[ 6.997002   7.9965024  8.996002 ]
   [ 9.995503  10.995004  11.994504 ]]

  [[12.994004  13.993505  14.993005 ]
   [15.992505  16.992004  17.991507 ]]]]
