# loss function, optimizer and dropout-layer

## Imports

In [1]:
from tensorflow.python.keras import backend as K

import numpy as np

import keras

## Loss functions

### Binary Absolute loss

In [2]:
def absolute_loss(y_true, y_pred):
    loss = K.abs(y_pred - y_true)
    return K.sum(loss)

In [3]:
y_true = np.array([1, 0, 1, 0])
y_pred = np.array([0.2, 0.1, 0.9, 0.05])

absolute_loss(y_true, y_pred).numpy()

np.float64(1.05)

### Binary Cross Entropy

In [4]:
y_true = np.array([1, 0, 1, 0])
y_pred = np.array([0.2, 0.1, 0.9, 0.05])

keras.losses.binary_crossentropy(y_true, y_pred).numpy()

np.float64(0.4678630595343259)

In [5]:
-(np.log(0.2) + np.log(0.9) + np.log(0.9) + np.log(0.95)) / 4

np.float64(0.4678630595343259)

### Categorical Cross Entropy

should be in on-hot format

In [6]:
# I have 4 classes and 3 data
y_true = np.array(
    [
        [1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 0, 1],
    ]
)
y_pred = np.array(
    [
        [0.8, 0.05, 0.1, 0.05],
        [0.2, 0.5, 0.2, 0.1],
        [0.1, 0.1, 0.1, 0.7],
    ]
)

keras.losses.categorical_crossentropy(y_true, y_pred).numpy()

array([0.22314355, 0.69314718, 0.35667494])

In [7]:
[-np.log(0.8), -np.log(0.5), -np.log(0.7)]

[np.float64(0.2231435513142097),
 np.float64(0.6931471805599453),
 np.float64(0.35667494393873245)]

## Sparse Categorical CrossEntropy

In [8]:
y_true = np.array(
    [
        0,
        1,
        3,
    ]
)
y_pred = np.array(
    [
        [0.8, 0.05, 0.1, 0.05],
        [0.2, 0.5, 0.2, 0.1],
        [0.1, 0.1, 0.1, 0.7],
    ]
)

keras.losses.sparse_categorical_crossentropy(y_true, y_pred).numpy()

array([0.22314355, 0.69314718, 0.35667494])

In [9]:
[-np.log(0.8), -np.log(0.5), -np.log(0.7)]

[np.float64(0.2231435513142097),
 np.float64(0.6931471805599453),
 np.float64(0.35667494393873245)]

### Use loss function with classes

mainly give us more configuration.

In [10]:
class AbsoluteLoss(keras.losses.Loss):
    def __init__(self):
        super().__init__()

    def call(self, y_true, y_pred):
        loss = K.abs(y_pred - y_true)
        return K.sum(loss)

In [11]:
y_true = np.array([1, 0, 1, 0])
y_pred = np.array([0.2, 0.1, 0.9, 0.05])

al = AbsoluteLoss()

al(y_true, y_pred).numpy()

np.float32(1.0500001)

In [12]:
# Binary Crossentropy
y_true = np.array([1, 0, 1, 0])
y_pred = np.array([0.2, 0.1, 0.9, 0.05])

bce = keras.losses.BinaryCrossentropy()

bce(y_true, y_pred).numpy()

np.float32(0.46786308)

In [13]:
# Categorical Crossentropy
y_true = np.array(
    [
        [1, 0, 0, 0],
        [0, 1, 0, 0],
        [0, 0, 0, 1],
    ]
)
y_pred = np.array(
    [
        [0.8, 0.05, 0.1, 0.05],
        [0.2, 0.5, 0.2, 0.1],
        [0.1, 0.1, 0.1, 0.7],
    ]
)

cce = keras.losses.CategoricalCrossentropy(reduction=None)

cce(y_true, y_pred).numpy()

array([0.22314355, 0.6931472 , 0.35667497], dtype=float32)

In [14]:
# Sparse Categorical Crossentropy
y_true = np.array(
    [
        0,
        1,
        3,
    ]
)
y_pred = np.array(
    [
        [0.8, 0.05, 0.1, 0.05],
        [0.2, 0.5, 0.2, 0.1],
        [0.1, 0.1, 0.1, 0.7],
    ]
)

scce = keras.losses.SparseCategoricalCrossentropy(reduction=None)

scce(y_true, y_pred).numpy()

array([0.22314355, 0.6931472 , 0.35667488], dtype=float32)

## Optimizer

In [15]:
sgd = keras.optimizers.SGD()

rmsprop = keras.optimizers.RMSprop()

adam = keras.optimizers.Adam()