# Session 6: Convolutional layer

In [2]:
import keras
import numpy as np

## Conv2D

* filter: number of output channels
* kernel_size
* strides
* padding:
    * "valid": no padding
    * "same": padding evenly to the left and right

### Normal example

In [7]:
a = np.arange(32, dtype=float).reshape(1, 4, 4, 2)

conv_2d = keras.layers.Conv2D(10, (2, 2))

result = conv_2d(a).numpy()

print("difference in shapes")
print(a.shape)
print(result.shape)
print("-" * 20)

print("1st channel")
print(a[0, :, :, 0])
print("-" * 20)

print("2nd channel")
print(a[0, :, :, 1])
print("-" * 20)

print("result of the 1st channel")
print(result[0, :, :, 0])
print("-" * 20)

print("result of the 2nd channel")
print(result[0, :, :, 1])
print("-" * 20)


difference in shapes
(1, 4, 4, 2)
(1, 3, 3, 10)
--------------------
1st channel
[[ 0.  2.  4.  6.]
 [ 8. 10. 12. 14.]
 [16. 18. 20. 22.]
 [24. 26. 28. 30.]]
--------------------
2nd channel
[[ 1.  3.  5.  7.]
 [ 9. 11. 13. 15.]
 [17. 19. 21. 23.]
 [25. 27. 29. 31.]]
--------------------
result of the 1st channel
[[1.974007  2.3745873 2.7751675]
 [3.5763285 3.9769084 4.377489 ]
 [5.1786494 5.5792303 5.9798098]]
--------------------
result of the 2nd channel
[[-0.1937983 -0.6892171 -1.1846361]
 [-2.175474  -2.6708937 -3.1663122]
 [-4.1571503 -4.6525693 -5.1479883]]
--------------------


### Strides example

In [9]:
a = np.arange(32, dtype=float).reshape(1, 4, 4, 2)

conv_2d = keras.layers.Conv2D(10, (2, 2), strides=(2, 1))

result = conv_2d(a).numpy()

print("difference in shapes")
print(a.shape)
print(result.shape)
print("-" * 20)

difference in shapes
(1, 4, 4, 2)
(1, 2, 3, 10)
--------------------


### Padding example

In [ ]:
a = np.arange(32, dtype=float).reshape(1, 4, 4, 2)

conv_2d = keras.layers.Conv2D(10, (2, 2), padding="same")

result = conv_2d(a).numpy()

print("difference in shapes")
print(a.shape)
print(result.shape)
print("-" * 20)

difference in shapes
(1, 4, 4, 2)
(1, 4, 4, 10)
--------------------
