# ResNet

In [1]:
import keras
import numpy as np


$y = \gamma \cdot \hat{x} + \beta$


In [15]:
a = np.arange(18, dtype=float).reshape(1, 3, 2, 3)

bn = keras.layers.BatchNormalization(beta_initializer="zeros", gamma_initializer="ones")

result = bn(a)

print(a)
print("-" * 20)
print(result.numpy())


[[[[ 0.  1.  2.]
   [ 3.  4.  5.]]

  [[ 6.  7.  8.]
   [ 9. 10. 11.]]

  [[12. 13. 14.]
   [15. 16. 17.]]]]
--------------------
[[[[ 0.          0.99950033  1.9990007 ]
   [ 2.998501    3.9980013   4.997502  ]]

  [[ 5.997002    6.9965024   7.9960027 ]
   [ 8.995503    9.995004   10.994504  ]]

  [[11.994004   12.993505   13.993005  ]
   [14.992505   15.992005   16.991507  ]]]]
