# Session 5: Average pooling layer

In [2]:
import keras
import numpy as np

## Max Pooling

In [9]:
a = np.arange(8, dtype=float).reshape(1, 2, 2, 2)

max_pooling_layer = keras.layers.MaxPool2D((2, 2), strides=1)

result = max_pooling_layer(a).numpy()

print("difference in shapes")
print(a.shape)
print(result.shape)
print("-" * 20)

print("1st channel")
print(a[0, :, :, 0])
print("-" * 20)

print("second channel")
print(a[0, :, :, 1])
print("-" * 20)

print("result of the 1st channel")
print(result[0, :, :, 0])
print("-" * 20)

print("result of the 2nd channel")
print(result[0, :, :, 1])
print("-" * 20)


difference in shapes
(1, 2, 2, 2)
(1, 1, 1, 2)
--------------------
1st channel
[[0. 2.]
 [4. 6.]]
--------------------
second channel
[[1. 3.]
 [5. 7.]]
--------------------
result of the 1st channel
[[6.]]
--------------------
result of the 2nd channel
[[7.]]
--------------------


In [10]:
a = np.arange(32, dtype=float).reshape(1, 4, 4, 2)

max_pooling_layer = keras.layers.MaxPool2D((2, 2), strides=1)

result = max_pooling_layer(a).numpy()


print("differences in shapes")
print(a.shape)
print(result.shape)
print("-" * 20)

print("1st channel")
print(a[0, :, :, 0])
print("-" * 20)

print("second channel")
print(a[0, :, :, 1])
print("-" * 20)

print("result of the 1st channel")
print(result[0, :, :, 0])
print("-" * 20)


print("result of the 2nd channel")
print(result[0, :, :, 1])
print("-" * 20)


differences in shapes
(1, 4, 4, 2)
(1, 3, 3, 2)
--------------------
1st channel
[[ 0.  2.  4.  6.]
 [ 8. 10. 12. 14.]
 [16. 18. 20. 22.]
 [24. 26. 28. 30.]]
--------------------
second channel
[[ 1.  3.  5.  7.]
 [ 9. 11. 13. 15.]
 [17. 19. 21. 23.]
 [25. 27. 29. 31.]]
--------------------
result of the 1st channel
[[10. 12. 14.]
 [18. 20. 22.]
 [26. 28. 30.]]
--------------------
result of the 2nd channel
[[11. 13. 15.]
 [19. 21. 23.]
 [27. 29. 31.]]
--------------------


## Gloal Max Pooling

In [11]:
a = np.arange(8, dtype=float).reshape(1, 2, 2, 2)

max_pooling_layer = keras.layers.GlobalMaxPooling2D()

result = max_pooling_layer(a).numpy()


print("difference in shapes")
print(a.shape)
print(result.shape)
print("-" * 20)

print("1st channel")
print(a[0, :, :, 0])
print("-" * 20)

print("second channel")
print(a[0, :, :, 1])
print("-" * 20)

print("result")
print(result)
print("-" * 20)

difference in shapes
(1, 2, 2, 2)
(1, 2)
--------------------
1st channel
[[0. 2.]
 [4. 6.]]
--------------------
second channel
[[1. 3.]
 [5. 7.]]
--------------------
result
[[6. 7.]]
--------------------


In [12]:
a = np.arange(32, dtype=float).reshape(1, 4, 4, 2)

max_pooling_layer = keras.layers.GlobalMaxPooling2D()

result = max_pooling_layer(a).numpy()

print("difference in shapes")
print(a.shape)
print(result.shape)
print("-" * 20)

print("1st channel")
print(a[0, :, :, 0])
print("-" * 20)

print("second channel")
print(a[0, :, :, 1])
print("-" * 20)

print("result")
print(result)
print("-" * 20)


difference in shapes
(1, 4, 4, 2)
(1, 2)
--------------------
1st channel
[[ 0.  2.  4.  6.]
 [ 8. 10. 12. 14.]
 [16. 18. 20. 22.]
 [24. 26. 28. 30.]]
--------------------
second channel
[[ 1.  3.  5.  7.]
 [ 9. 11. 13. 15.]
 [17. 19. 21. 23.]
 [25. 27. 29. 31.]]
--------------------
result
[[30. 31.]]
--------------------
