# Session 6: Convolutional layer

In [1]:
import keras
import numpy as np

## Conv2D

In [ ]:
a = np.arange(18, dtype=float).reshape(1, 3, 3, 2)

conv_2d = keras.layers.Conv2D(10, (2, 2))

result = conv_2d(a).numpy()

print("difference in shapes")
print(a.shape)
print(result.shape)
print("-" * 20)

print("1st channel")
print(a[0, :, :, 0])
print("-" * 20)

print("2nd channel")
print(a[0, :, :, 1])
print("-" * 20)

print("result of the 1st channel")
print(result[0, :, :, 0])
print("-" * 20)

print("result of the 2nd channel")
print(result[0, :, :, 1])
print("-" * 20)


difference in shapes
(1, 3, 3, 2)
(1, 2, 2, 10)
--------------------
1st channel
[[ 0.  2.  4.]
 [ 6.  8. 10.]
 [12. 14. 16.]]
--------------------
second channel
[[ 1.  3.  5.]
 [ 7.  9. 11.]
 [13. 15. 17.]]
--------------------
result of the 1st channel
[[-1.8230822 -2.6907558]
 [-4.4261036 -5.2937775]]
--------------------
result of the 2nd channel
[[-3.5358944 -5.023037 ]
 [-7.9973216 -9.484464 ]]
--------------------
